/**
 * ToolSpec — the document that describes one personal AI tool.
 *
 * The whole app is a pair of functions around this type:
 *   1. תיאור בשפה חופשית  ->  ToolSpec   (engine/localBuilder.ts, engine/claude.ts)
 *   2. ToolSpec           ->  לוח שליטה  (pages/Console.tsx)
 *
 * A spec is plain JSON so it can be exported, imported, edited by hand,
 * or generated by Claude with structured outputs.
 */

export type FieldType = 'text' | 'longtext' | 'select' | 'date' | 'number'

/** קלט — מה שהמשתמש מזין לכלי לפני שהוא לוחץ על פעולה. */
export interface SpecField {
  id: string
  label: string
  type: FieldType
  placeholder?: string
  /** for type === 'select' */
  options?: string[]
  required?: boolean
}

export type ControlType = 'slider' | 'toggle' | 'choice'

/** בקרה — סליידר/מתג/בורר שמכוון את ההתנהגות של הכלי (נכנס לפרומפט). */
export interface SpecControl {
  id: string
  label: string
  type: ControlType
  hint?: string
  /** slider */
  min?: number
  max?: number
  step?: number
  /** slider: מה המשמעות של הקצוות, כדי שה-AI יבין את הסקאלה */
  lowLabel?: string
  highLabel?: string
  /** choice */
  options?: string[]
  /** slider: number | toggle: boolean | choice: string */
  default: number | boolean | string
}

export type ActionOutput = 'text' | 'items' | 'both'

/** פעולה — כפתור על לוח השליטה. */
export interface SpecAction {
  id: string
  label: string
  /** אמוג'י יחיד שמופיע על הכפתור */
  icon?: string
  /** הוראה ל-AI. תומכת בהחלפות {{fieldId}} ו-{{controlId}}. */
  prompt: string
  output: ActionOutput
  /** אם הפעולה מייצרת פריטים — לאיזה אוסף הם נכנסים */
  target?: string
  /** כפתור ראשי מודגש */
  primary?: boolean
}

/** אוסף — הזיכרון של הכלי: רשימת פריטים עם סטטוסים. */
export interface SpecCollection {
  id: string
  label: string
  /** שם פריט יחיד, למשל "תיקון מיקס" */
  itemLabel: string
  statuses: string[]
  /** האם לפריטים יש חותמת מיקום/זמן (למשל 01:24 בטראק) */
  hasTimecode?: boolean
  emptyText?: string
}

export interface ToolSpec {
  id: string
  name: string
  tagline: string
  icon: string
  /** ההקשר הקבוע שנשלח ל-AI בכל פעולה */
  systemPrompt: string
  fields: SpecField[]
  controls: SpecControl[]
  actions: SpecAction[]
  collections: SpecCollection[]
  createdAt: string
  updatedAt: string
  /** מאיזה תיאור הכלי נבנה — נשמר כדי שאפשר יהיה לבנות מחדש */
  sourceBrief?: string
  /** 'local' = מנוע התבניות המקומי, 'claude' = נבנה על ידי Claude */
  builtBy?: 'local' | 'claude'
}

export interface CollectionItem {
  id: string
  collectionId: string
  title: string
  detail?: string
  status: string
  /** למשל "01:24" או "יום ג׳ 10:00" */
  at?: string
  tags?: string[]
  createdAt: string
}

export interface RunLogEntry {
  id: string
  toolId: string
  actionId: string
  actionLabel: string
  text: string
  itemCount: number
  engine: 'claude' | 'demo'
  createdAt: string
}

/** המצב השמור של כלי מסוים: ערכי שדות, בקרות, אוסף פריטים ופלט אחרון. */
export interface ToolState {
  fieldValues: Record<string, string>
  controlValues: Record<string, number | boolean | string>
  items: CollectionItem[]
  log: RunLogEntry[]
}

export interface Settings {
  apiKey: string
  /** ברירת מחדל: 'auto' — Claude אם יש מפתח, אחרת מצב הדגמה */
  engine: 'auto' | 'demo'
}

export const EMPTY_TOOL_STATE: ToolState = {
  fieldValues: {},
  controlValues: {},
  items: [],
  log: [],
}
